### ISSUE TITLE
Anchor - <a> active, hover attributes missing

### ISSUE THREAD

**Issue by gsalunke** [FifthTry/ftd#101]
![achor-css-attributes](https://user-images.githubusercontent.com/68585007/152630274-6f82a858-4e9d-4188-a68c-020c5a99acda.PNG)

**Comment by amitu** [comment]
We will allow people to write:

```ftd
-- ftd.text foo: some text
link: /
color if $LINK-ACTIVE: red
color if $VISITED: green
```

Etc. All style attributes can be conditional on these new variables. We will not allow non style attributes to use these variables, eg `link if $VISITED: /` is not allowed, it will be a compilation error.

For each component containing such attributes we will create a class. So eg for `foo` we will create:

```css
.<doc-id>-foo:active {
     color: red;
}
.<doc-id>-foo:visited {
     color: green;
}
```

We will also allow them on elements:

```ftd
-- ftd.text: 
link: /
color if $LINK-ACTIVE: red
color if $VISITED: green
```

For them we will auto create some ID and use that for CSS:

```css
#<element-id>-foo:active {
     color: red;
}
#<element-id>-foo:visited {
     color: green;
}
```
