### ISSUE TITLE
use css for dynamic kernel properties

### ISSUE THREAD

**Issue by amitu** [FifthTry/ftd#186]
Properties like font-family, font-size, color, background-colour etc currently dependent on ftd variables `ftd.dark-mode` and `ftd.device`, and we are creating dependency tree etc for them. 

These properties occur too many times in generated page, so modifying say `ftd.dark-mode` modifies virtually every dom node in the page, which would be quite slow on run time.

Instead of putting inline styles for dynamic kernel properties we should use style. Eg

```ftd
-- ftd.text: hello
role: $fpm.design.type.body-large
color: $fpm.degin.color.brand.on-primary-action
background-color: $fpm.degin.color.brand.primary-action
```

Leads to:

```html
<div style="font-family: serif; font-size: 24px; line-height: 28px...">hello</div>
```

We should instead generate:

```html
<div class="aed3see ead3eae eea2211">hello</div>
```

Say `aed3see=hash(role: $fpm.design.type.body-large)`, `ead3eae=hash(color: $fpm.degin.color.brand.on-primary-action)` and `eea2211=hash(background-color: $fpm.degin.color.brand.primary-action)`.

Since type only depends on `$ftd.device`

```css
body.desktop > .aed3see { // role: $fpm.design.type.body-large
    font-family: serif;
    font-size: 24px;
    line-height: 28px;
}
body.tablet > .aed3see { 
    font-family: serif;
    font-size: 20px;
    line-height: 24px;
}
body.tablet > .aed3see { 
  ...
}
```

Similarly `color` and `background-colour` only changes on `$ftd.dark-mode`:

```css
body.dark-mode > . ead3eae { // color: $fpm.degin.color.brand.on-primary-action
    font-family: serif;
    font-size: 24px;
    line-height: 28px;
}
body.light-mode > . ead3eae {
  ...
}
```

This way when either `ftd.dark-mode` or `ftd.device` changes we only update a class on body, so this would be much faster, both at build time and at runtime. Also since we are not going to store dependencies the generated HTML would be smaller as well.
